version: '2.1'
orbs:
  flutter: checkmoney/flutter@1.1.1

jobs:
  build:
    docker:
      - image: cimg/android:2022.03
    steps:
      - checkout

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
      - flutter/lint
      - flutter/test
