name: utils
description: Utility methods for famnom_flutter
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0"

dependencies:
  intl: ^0.17.0

dev_dependencies:
  constants:
    path: ../../packages/constants
  flutter_test:
    sdk: flutter
  test: ^1.16.4
  very_good_analysis: ^2.4.0
