name: famnom_api
description: Dart package which manages the famnom APIs.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  http: ^0.13.0
  json_annotation: ^4.5.0
  meta: ^1.3.0
  shared_preferences: ^2.0.13
  very_good_analysis: ^2.4.0

dev_dependencies:
  build_runner: ^2.1.10
  constants:
    path: ../../packages/constants
  coverage: ^1.0.3
  environments:
    path: ../../packages/environments
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  test: ^1.16.4
